### ISSUE TITLE
confd crashes with zookeeper

### ISSUE THREAD

**Issue by nogece** [kelseyhightower/confd#299]
following shell interaction gives all details :
```
c@u:~$ find /tmp/confd/
/tmp/confd/
/tmp/confd/templates
/tmp/confd/templates/myconfig.conf.tmpl
/tmp/confd/conf.d
/tmp/confd/conf.d/myconfig.toml
c@u:~$ cat /tmp/confd/templates/myconfig.conf.tmpl
[myconfig]
database_url = {{getv "/myapp/database/url"}}
database_user = {{getv "/myapp/database/user"}}
c@u:~$ cat /tmp/confd/conf.d/myconfig.toml
[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.conf"
keys = [
    "/myapp/database/url",
    "/myapp/database/user",
]
c@u:~$ ~/Downloads/confd-0.9.0-linux-amd64 -onetime -backend zookeeper -confdir="/tmp/confd" -log-level=debug -interval=10
2015-05-29T15:12:26+02:00 u /home/c/Downloads/confd-0.9.0-linux-amd64[19065]: INFO Backend set to zookeeper
2015-05-29T15:12:26+02:00 u /home/c/Downloads/confd-0.9.0-linux-amd64[19065]: INFO Starting confd
2015-05-29T15:12:26+02:00 u /home/c/Downloads/confd-0.9.0-linux-amd64[19065]: INFO Backend nodes set to 
2015-05-29T15:12:26+02:00 u /home/c/Downloads/confd-0.9.0-linux-amd64[19065]: DEBUG Loading template resources from confdir /tmp/confd
2015-05-29T15:12:26+02:00 u /home/c/Downloads/confd-0.9.0-linux-amd64[19065]: DEBUG Loading template resource from /tmp/confd/conf.d/myconfig.toml
2015-05-29T15:12:26+02:00 u /home/c/Downloads/confd-0.9.0-linux-amd64[19065]: DEBUG Retrieving keys from store
2015-05-29T15:12:26+02:00 u /home/c/Downloads/confd-0.9.0-linux-amd64[19065]: DEBUG Key prefix set to /
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x59b007 pc=0x59b007]

goroutine 6 [running]:
github.com/samuel/go-zookeeper/zk.(*Conn).connect(0xc20803cb60)
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go:187 +0x47
github.com/samuel/go-zookeeper/zk.(*Conn).loop(0xc20803cb60)
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go:210 +0x56
github.com/samuel/go-zookeeper/zk.func·001()
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go:156 +0x2c
created by github.com/samuel/go-zookeeper/zk.ConnectWithDialer
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go:160 +0x4b5

goroutine 1 [chan receive]:
github.com/samuel/go-zookeeper/zk.(*Conn).request(0xc20803cb60, 0xc200000003, 0x69de20, 0xc20801cf80, 0x69de80, 0xc208049130, 0x0, 0x40a07e, 0x0, 0x0)
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go:614 +0xcc
github.com/samuel/go-zookeeper/zk.(*Conn).Exists(0xc20803cb60, 0xc20801cee0, 0x13, 0x2, 0x0, 0x0, 0x0)
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go:728 +0x111
github.com/kelseyhightower/confd/backends/zookeeper.(*Client).GetValues(0xc208046040, 0xc20801ce60, 0x2, 0x2, 0x2, 0x0, 0x0)
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/backends/zookeeper/client.go:61 +0x14a
github.com/kelseyhightower/confd/resource/template.(*TemplateResource).setVars(0xc208072900, 0x0, 0x0)
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/resource/template/resource.go:92 +0x171
github.com/kelseyhightower/confd/resource/template.(*TemplateResource).process(0xc208072900, 0x0, 0x0)
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/resource/template/resource.go:242 +0x71
github.com/kelseyhightower/confd/resource/template.process(0xc208046100, 0x1, 0x1, 0x0, 0x0)
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/resource/template/processor.go:26 +0x99
github.com/kelseyhightower/confd/resource/template.Process(0x7fffb4eb7b6d, 0xa, 0xc20801c580, 0x11, 0x0, 0x7bbc70, 0x1, 0x7f953f783218, 0xc208046040, 0xc20801c5c0, ...)
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/resource/template/processor.go:20 +0xc8
main.main()
	/Users/bacongobbler/go/src/github.com/kelseyhightower/confd/confd.go:31 +0x291

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by nogece** [comment]
Maybe I should have "filled the severity field": this is an issue that renders confd for zookeeper  useless. It (the tutorial example) just doesnt work at all for me .

**Comment by bacongobbler** [comment]
ping @sheepkiller

**Comment by sheepkiller** [comment]
Hi @nogece, 

Which version of zookeeper are you running ?

thanks

**Comment by sheepkiller** [comment]
There's no default node for zookeeper backend. Can you please re-test with "-node=localhost:2181" ?

thanks
clem

**Comment by kelseyhightower** [comment]
Looks like we merged the fix for this. Thanks @sheepkiller
