### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by m1no** [kelseyhightower/confd#322]
I template generation works and all the data is correct but after some seconds the daemon dies. I'm using the latest 0.10 release.

```
root@proxy:/# cat /etc/confd/conf.d/haproxy.toml
[template]
prefix = "/test/"
src = "haproxy.cfg.tmpl"
dest = "/tmp/haproxy.cfg"
owner = "haproxy"
mode = "0644"
keys = [
  "/proxy",
  "/subs",
]
reload_cmd = "/usr/bin/sv restart haproxy"
check_cmd = "/usr/sbin/haproxy -c -f {{.src}}"

root@proxy:/#confd -watch -backend consul -node my.example.com:80
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ff627]

goroutine 43 [running]:
runtime.panic(0x72b9c0, 0x942bd3)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/kelseyhightower/confd/backends/consul.func·001()
	/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/backends/consul/client.go:56 +0xe7
created by github.com/kelseyhightower/confd/backends/consul.(*Client).WatchPrefix
	/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/backends/consul/client.go:57 +0x121

goroutine 16 [select, 1 minutes]:
main.main()
	/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/confd.go:50 +0x7d0

goroutine 19 [finalizer wait, 1 minutes]:
runtime.park(0x415d70, 0x9476c8, 0x945949)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x9476c8, 0x945949)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 1 minutes]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc2080012a0)
	/usr/local/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc20800e190)
	/usr/local/go/src/pkg/sync/waitgroup.go:129 +0x14b
github.com/kelseyhightower/confd/resource/template.(*watchProcessor).Process(0xc20800e120)
	/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/resource/template/processor.go:88 +0x1ad
created by main.main
	/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/confd.go:46 +0x466

goroutine 22 [select, 1 minutes]:
github.com/kelseyhightower/confd/backends/consul.(*Client).WatchPrefix(0xc20802e038, 0xc208000ac7, 0x7, 0x2336c, 0xc2080042a0, 0x2336c, 0x0, 0x0)
	/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/backends/consul/client.go:59 +0x21e
github.com/kelseyhightower/confd/resource/template.(*watchProcessor).monitorPrefix(0xc20800e120, 0xc208032700)
	/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/resource/template/processor.go:94 +0xcb
created by github.com/kelseyhightower/confd/resource/template.(*watchProcessor).Process
	/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/resource/template/processor.go:86 +0x166

goroutine 47 [select]:
net/http.(*persistConn).writeLoop(0xc208030000)
	/usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 27 [select]:
net.func·019()
	/usr/local/go/src/pkg/net/dnsclient_unix.go:184 +0x2ab
created by net.loadConfig
	/usr/local/go/src/pkg/net/dnsclient_unix.go:212 +0x153

goroutine 46 [runnable]:
net/http.(*persistConn).readLoop(0xc208030000)
	/usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:600 +0x93f
2015-08-18T13:19:28Z proxy confd[16394]: WARNING Skipping confd config file.
```

**Comment by petere** [comment]
I see this too, with the consul backend, when the consul service is not yet running (e.g., after a reboot of the entire system).

**Comment by bacongobbler** [comment]
@m1no do you mean the 0.11 release?

**Comment by petere** [comment]
I can still reproduce this with the 0.11.0 release.

**Comment by bacongobbler** [comment]
The error's pointing at lines 56 and 57 [here](https://github.com/kelseyhightower/confd/blob/v0.11.0/src/github.com/kelseyhightower/confd/backends/consul/client.go#L56-L57) but it looks like a --watch error with confd.

**Comment by petere** [comment]
Without `-watch` it just hangs if consul is not up. Not sure if that is intentional either.

**Comment by kelseyhightower** [comment]
This issue is now fixed on master. If consul is not up the confd will print the following error messages:

```
ERROR Get http://127.0.0.1:8500/v1/kv//test/?recurse=: dial tcp 127.0.0.1:8500: getsockopt: connection refused
```

This works for both watches and interval runs.
