### ISSUE TITLE
zookeeper client close connection WARN

### ISSUE THREAD

**Issue by fxpz** [kelseyhightower/confd#447]
Hi,

I'm using confd 0.12.0-dev with zookeeper backend and watch enabled.
In zookeeper leader log I see many of this WARN:

```
WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x95502585c143a0b, likely client has closed socket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)
```

I'm not sure but it seems that confd don't correctly close zookeeper connections.
I wrote a test script that perform a zookeeper connection and exits without close connection and I get the same WARN.
Is there a way to fix this?
A doubt: if watch is enabled why connection are closed? it should remain active or I wrong something?

thanks,
Fx

**Comment by matarrese** [comment]
Hi, I'm getting the same error? Any luck?
