### ISSUE TITLE
Crashed while using -watch=true with consul backend

### ISSUE THREAD

**Issue by internalerror** [kelseyhightower/confd#482]
confd version is 0.11.0, Ubuntu 16.04 x64

$**sudo ./confd -log-level="debug" -watch=true -backend consul -node myconsul.domain -confdir="."**
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: INFO Backend set to consul
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: INFO Starting confd
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: INFO Backend nodes set to myconsul.domain
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG Loading template resources from confdir .
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG Loading template resource from conf.d/nginx.toml
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG Retrieving keys from store
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG Key prefix set to /
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG Using source template templates/nginx.tmpl
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG Compiling source template templates/nginx.tmpl
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG Comparing candidate config to /home/xxx/confd/dest/nginx.conf
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: INFO /home/xxx/confd/dest/nginx.conf has md5sum d1561e807a574723ea4cdf216bc5f10e should be 0409be86f8bb1193c1085278a81bc416
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: INFO Target config /home/xxx/confd/dest/nginx.conf out of sync
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG Overwriting target config /home/xxx/confd/dest/nginx.conf
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG Running /usr/local/nginx/bin/nginx -s reload
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: DEBUG ""
2016-09-13T19:39:32+08:00 xxx ./confd[19535]: INFO Target config /home/xxx/confd/dest/nginx.conf has been updated
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x524afb]

goroutine 23 [running]:
github.com/kelseyhightower/confd/backends/consul.func·001()
        /Users/bacongobbler/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/backends/consul/client.go:86 +0xfb
created by github.com/kelseyhightower/confd/backends/consul.(*ConsulClient).WatchPrefix
        /Users/bacongobbler/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/backends/consul/client.go:87 +0x1c7

goroutine 1 [select, 1 minutes]:
main.main()
        /Users/bacongobbler/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/confd.go:57 +0x9dd

goroutine 5 [syscall, 1 minutes]:
os/signal.loop()
        /usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [semacquire, 1 minutes]:
sync.(_WaitGroup).Wait(0xc2080842b0)
        /usr/local/Cellar/go/1.4.2/libexec/src/sync/waitgroup.go:132 +0x169
github.com/kelseyhightower/confd/resource/template.(_watchProcessor).Process(0xc208084240)
        /Users/bacongobbler/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/resource/template/processor.go:89 +0x1e3
created by main.main
        /Users/bacongobbler/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/confd.go:52 +0x594

goroutine 7 [select]:
github.com/kelseyhightower/confd/backends/consul.(_ConsulClient).WatchPrefix(0xc208036088, 0x0, 0x0, 0x7f97, 0xc20806c540, 0x7f97, 0x0, 0x0)
        /Users/bacongobbler/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/backends/consul/client.go:89 +0x2f1
github.com/kelseyhightower/confd/resource/template.(_watchProcessor).monitorPrefix(0xc208084240, 0xc208082c00)
        /Users/bacongobbler/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/resource/template/processor.go:95 +0xce
created by github.com/kelseyhightower/confd/resource/template.(*watchProcessor).Process
        /Users/bacongobbler/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/resource/template/processor.go:87 +0x19c

goroutine 28 [select]:
net/http.(_persistConn).writeLoop(0xc20803a160)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:661 +0xcbc

goroutine 27 [runnable]:
net/http.(_persistConn).readLoop(0xc20803a160)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:928 +0x9ce
created by net/http.(_Transport).dialConn
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net.func·019()
        /usr/local/Cellar/go/1.4.2/libexec/src/net/dnsclient_unix.go:241 +0x2f4
created by net.loadConfig
        /usr/local/Cellar/go/1.4.2/libexec/src/net/dnsclient_unix.go:269 +0x20c

**Comment by okushchenko** [comment]
Please, reopen if this issue is still present for you in 0.12.0-dev. Closing for now.
