### ISSUE TITLE
Panic on changing a watched file

### ISSUE THREAD

**Issue by jschilperoord** [kelseyhightower/confd#764]
I am using `confd 0.16.0 (Git SHA: 7217b0ca, Go Version: go1.10.2)` inside a Centos 7 container with the file backend in watch mode:

`confd -watch -backend file -file /etc/confd/yaml/config.yaml`

Changing the yaml generates the following error/panic:

`panic: send on closed channel
goroutine 11 [running]:
github.com/kelseyhightower/confd/backends/file.(*Client).watchChanges.func1(0xc4201e59f0, 0xc42027ea20, 0xc42027e0c0, 0x0, 0xfc6000001a4)
	/go/src/github.com/kelseyhightower/confd/backends/file/client.go:122 +0x1f7
created by github.com/kelseyhightower/confd/backends/file.(*Client).watchChanges
	/go/src/github.com/kelseyhightower/confd/backends/file/client.go:111 +0xb1`

Look similar to #715. But I assume I am using the most recent confd ?

**Comment by alexeyryzhikov** [comment]
Run into this issue as well for Docker mounted files.
As a workaround you can pass the poll interval explicitly (ex. `confd -backend=file -file=/config.yaml -interval 1`)

**Comment by dmakhno** [comment]
bump this too.
is it 0.17 milestone as #715 ?
